services:
  - type: worker
    name: tweet-notify-bot
    runtime: python
    repo: https://github.com/tu-usuario/tu-repo
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
